//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by W3DView.rc
//
#define IDC_RECALC                      3
#define IDC_CLEAR                       3
#define IDC_BROWSE                      3
#define IDC_RESTORE                     3
#define IDC_RESET                       3
#define IDOK2                           3
#define IDC_SOUND_DEFINITION_LIBRARY_BROWSE_BUTTON 3
#define IDC_ADVANCED                    4
#define IDC_APPLY                       4
#define IDC_SOUND_INI_BROWSE_BUTTON     4
#define IDC_REPLACE_TEXTURE             5
#define IDC_SOUND_PATH_BROWSE_BUTTON    5
#define IDC_RESTORE_TEXTURE             6
#define IDD_ABOUTBOX                    100
#define IDD_FORMVIEW                    101
#define IDD_PROP_PAGE_MESH              106
#define IDD_PROP_PAGE_EMITTER_GEN       107
#define IDR_MAINFRAME                   128
#define IDR_W3DVIETYPE                  129
#define IDD_COLOR_PICKER                129
#define IDB_MARKER                      130
#define IDD_COLOR_FORM                  130
#define IDC_CURSOR_GRAB                 131
#define IDB_KEYFRAME_V                  131
#define IDC_CURSOR_ZOOM                 132
#define IDB_KEYFRAME_H                  132
#define IDI_ICON1                       133
#define IDD_DIALOG1                     134
#define IDR_LOD_MENU                    135
#define IDR_ANI_MENU                    136
#define IDD_DISPLAYSPEED                136
#define IDR_HIERARCHY_MENU              137
#define IDI_ANIMATION                   137
#define IDI_MESH                        138
#define IDR_AGGREGATE_MENU              138
#define IDD_LIGHT_AMBIENT_DIALOG        139
#define IDI_MATERIAL                    139
#define IDD_RENDER_DEVICE_SELECTOR      140
#define IDB_BITMAP1                     140
#define IDI_HIERARCHY                   140
#define IDD_PROP_PAGE_HIERARCHY         141
#define IDI_LOD                         141
#define IDD_LIGHT_SCENE_DIALOG          142
#define IDD_BACKGROUND_COLOR            143
#define IDD_SAVE_SETTING                144
#define IDD_SAVE_SETTINGS               144
#define IDD_EDIT_LOD                    145
#define IDD_BACKGROUND_OBJECT           146
#define IDD_PROP_PAGE_ANIMATION         147
#define IDD_BACKGROUND_BMP              148
#define IDD_PROP_PAGE_EMITTER_PARTICLE  149
#define IDB_LOCK_X_UP                   150
#define IDD_PROP_PAGE_EMITTER_PHYSICS   150
#define IDI_USER                        150
#define IDD_PROP_PAGE_EMITTER_COLOR     151
#define IDI_PHYSICS                     151
#define IDB_LOCK_Y_UP                   152
#define IDD_PROP_PAGE_EMITTER_USER      152
#define IDI_PARTICLE                    152
#define IDB_LOCK_Z_UP                   153
#define IDI_COLOR                       153
#define IDD_BONE_MANAGEMENT             153
#define IDB_LOCK_X_DN                   154
#define IDI_EMITTER                     154
#define IDB_LOCK_Y_DN                   155
#define IDI_BONE                        155
#define IDB_LOCK_Z_DN                   156
#define IDI_FOLDER                      156
#define IDD_MAKE_AGGREGATE              156
#define IDB_ROTATE_Z_UP                 157
#define IDD_TEXTURE_MANAGMENT           157
#define IDD_TEXTURE_SETTINGS            158
#define IDB_ROTATE_Z_DN                 159
#define IDB_PLAY_UP                     160
#define IDI_MESH_FOLDER                 160
#define IDB_PLAY_DN                     161
#define IDI_DEF_TEXTURE                 161
#define IDB_STOP_UP                     162
#define IDB_STOP_DN                     163
#define IDD_OPACITY                     163
#define IDB_FFWD_DN                     164
#define IDD_VOLUME_RANDOMIZER           164
#define IDB_PAUSE_UP                    165
#define IDI_VOLUME                      165
#define IDB_PAUSE_DN                    166
#define IDD_PARTICLE_SIZE               166
#define IDB_REVERSE_UP                  167
#define IDB_REVERSE_DN                  168
#define IDB_FFWD_UP                     169
#define IDD_PROP_PAGE_ADVANIM_MIXING    172
#define IDD_PROP_PAGE_ADVANIM_REPORT    173
#define IDI_OBJECT                      174
#define IDD_CAMERA_SETTINGS             174
#define IDI_AGGREGATE                   175
#define IDI_TEXTURE                     176
#define IDI_RENAME                      177
#define IDI_SIZE                        178
#define IDD_COLOR_SEL                   179
#define IDI_CAMERA                      179
#define IDD_TEXTURE_MANAGMENT1          180
#define IDD_RENAME_AGGREGATE            181
#define IDR_INSTANCES_TOOLBAR           182
#define IDD_PROP_PAGE_EMITTER_SIZE      182
#define IDD_TEXTURE_PATHS               183
#define IDI_ANIMATION_COMPRESSED        184
#define IDD_RESOLUTION                  185
#define IDI_RESOLUTION                  186
#define IDI_ANIMATION_COMPRESSED_DELTA  187
#define IDI_SPHERE                      188
#define IDI_PRIMITIVES                  189
#define IDD_OPACITY_VECTOR              189
#define IDI_OPACITY_VECTOR              190
#define IDD_ADD_TO_LINEUP               191
#define IDI_LINEUP                      192
#define IDI_SOUND                       193
#define IDI_LINE                        194
#define IDD_CAMERA_DISTANCE             195
#define IDI_ROTATION                    195
#define IDD_SOUND_EDIT                  196
#define IDI_FRAME                       196
#define IDD_PROP_PAGE_EMITTER_LINEGROUP 201
#define IDD_PARTICLE_BLUR_TIME_KEY      202
#define IDD_GAMMA_DIALOG                203
#define IDD_PLAY_SOUND_EFFECT           204
#define IDB_GAMMA                       204
#define IDD_ANIMATED_SOUND_DIALOG       205
#define IDC_HUE_PICKER                  1000
#define IDC_WHITENESS_BAR               1001
#define IDC_COLLISION_TYPE_PHYSICAL     1002
#define IDC_COLOR_BAR                   1002
#define IDC_RED_BAR                     1002
#define IDC_COLLISION_TYPE_PROJECTILE   1003
#define IDC_OPACITY_BAR                 1003
#define IDC_GREEN_BAR                   1003
#define IDC_HIDDEN                      1004
#define IDC_SIZE_BAR                    1004
#define IDC_VECTOR_BAR                  1004
#define IDC_BLUE_BAR                    1004
#define IDC_MESH_TYPE_NORMAL            1005
#define IDC_SCALE_BAR_Y                 1005
#define IDC_RENDER_DEVICE_COMBO         1006
#define IDC_MESH_TYPE_COLLISION_BOX     1006
#define IDC_SCALE_BAR_Z                 1006
#define IDC_OUTER_SCALE_BAR_Y           1006
#define IDC_MESH_TYPE_SKIN              1007
#define IDC_DEVICE_NAME_STATIC          1008
#define IDC_MESH_TYPE_SHADOW            1008
#define IDC_DEVICE_VENDOR_STATIC        1009
#define IDC_DEVICE_PLATFORM_STATIC      1010
#define IDC_DRIVER_NAME_STATIC          1011
#define IDC_VERTEX_COUNT                1011
#define IDC_ORIG_COLOR_BAR              1011
#define IDC_DRIVER_VENDOR_STATIC        1012
#define IDC_POLYGON_COUNT               1012
#define IDC_CURRENT_COLOR_BAR           1012
#define IDC_DRIVER_VERSION_STATIC       1013
#define IDC_SUBOBJECT_LIST              1013
#define IDC_TOTAL_TIME                  1013
#define IDC_HARDWARE_NAME_STATIC        1014
#define IDC_TOTAL_POLYGONS              1014
#define IDC_HARDWARE_VENDOR_STATIC      1015
#define IDC_SUBOBJECTS                  1015
#define IDC_PLAY                        1015
#define IDC_HARDWARE_CHIPSET_STATIC     1016
#define IDC_DESCRIPTION                 1016
#define IDC_COLORDEPTH_16               1017
#define IDC_USER_TEXT                   1017
#define IDC_COLORDEPTH_24               1018
#define IDC_LIST1                       1018
#define IDC_MESH_TEXTURE_LIST_CTRL      1018
#define IDC_ANIM_REPORT                 1018
#define IDC_SETTINGS_GROUP              1019
#define IDC_DRIVER_NAME                 1019
#define IDC_EDIT1                       1020
#define IDC_START_OPACITY_EDIT          1020
#define IDC_RED_EDIT                    1020
#define IDC_AGGREGATE_NAME              1020
#define IDC_DISTANCE_EDIT               1020
#define IDC_HFOV_EDIT                   1020
#define IDC_PATH1                       1020
#define IDC_SIZE_X_EDIT                 1020
#define IDC_SOUND_DEFINITION_LIBRARY_EDIT 1020
#define IDC_EDIT2                       1021
#define IDC_PROGRAMMER_SETTINGS_EDIT    1021
#define IDC_GREEN_EDIT                  1021
#define IDC_FRAME_COUNT_EDIT            1021
#define IDC_RED_RANDOM_EDIT             1021
#define IDC_VFOV_EDIT                   1021
#define IDC_PATH2                       1021
#define IDC_SIZE_Y_EDIT                 1021
#define IDC_SOUND_INI_EDIT              1021
#define IDC_SPIN1                       1022
#define IDC_ZPOS_EDIT                   1022
#define IDC_START_OPACITY_SPIN          1022
#define IDC_BLUE_EDIT                   1022
#define IDC_FRAME_COUNT_SPIN            1022
#define IDC_START_ATTENUATION_EDIT      1022
#define IDC_EDIT3                       1022
#define IDC_GREEN_RANDOM_EDIT           1022
#define IDC_HFOV_SPIN                   1022
#define IDC_SIZE_Z_EDIT                 1022
#define IDC_OUTER_SIZE_X_EDIT           1022
#define IDC_SOUND_FILE_PATH_EDIT        1022
#define IDC_SPIN2                       1023
#define IDC_SPEED_SLIDER                1023
#define IDC_PARTICLE_CAP_MAX_SPIN       1023
#define IDC_END_OPACITY_SPIN            1023
#define IDC_BLUE_SPIN                   1023
#define IDC_FPS_EDIT                    1023
#define IDC_END_ATTENUATION_EDIT        1023
#define IDC_RED_RANDOM_SPIN             1023
#define IDC_MAX_PARTICLES_SPIN          1023
#define IDC_VFOV_SPIN                   1023
#define IDC_OUTER_SIZE_Y_EDIT           1023
#define IDC_SLIDER_RED                  1024
#define IDC_PARTICLE_EMITION_RATE_SPIN  1024
#define IDC_FPS_SPIN                    1024
#define IDC_SPIN3                       1024
#define IDC_GREEN_RANDOM_SPIN           1024
#define IDC_EMISSION_RATE_SPIN          1024
#define IDC_NEAR_CLIP_EDIT              1024
#define IDC_INFINITE_LOOPS_CHECK        1024
#define IDC_RED_GRADIENT                1025
#define IDC_PARTICLE_CAP_TIME_SPIN      1025
#define IDC_ACCELERATION_Y_SPIN         1025
#define IDC_EDIT4                       1025
#define IDC_BLUE_RANDOM_EDIT            1025
#define IDC_BURST_SIZE_SPIN             1025
#define IDC_NEAR_CLIP_SPIN              1025
#define IDC_STOP_WHEN_HIDDEN_CHECK      1025
#define IDC_SLIDER_GREEN                1026
#define IDC_ACCELERATION_Z_SPIN         1026
#define IDC_PARTICLE_POSITION_RANDOM_SPIN 1026
#define IDC_SPIN4                       1026
#define IDC_BLUE_RANDOM_SPIN            1026
#define IDC_FAR_CLIP_EDIT               1026
#define IDC_MERGE_ABORT_FACTOR_SPIN     1026
#define IDC_GREEN_GRADIENT              1027
#define IDC_VELOCITY_X_SPIN             1027
#define IDC_EDIT5                       1027
#define IDC_OPACITY_RANDOM_EDIT         1027
#define IDC_FAR_CLIP_SPIN               1027
#define IDC_UVTILING_SPIN               1027
#define IDC_SLIDER_BLUE                 1028
#define IDC_VELOCITY_Y_SPIN             1028
#define IDC_SPIN5                       1028
#define IDC_OPACITY_RANDOM_SPIN         1028
#define IDC_LENS_EDIT                   1028
#define IDC_UPERSEC_SPIN                1028
#define IDC_BLUE_GRADIENT               1029
#define IDC_VELOCITY_Z_SPIN             1029
#define IDC_LENS_SPIN                   1029
#define IDC_VPERSEC_SPIN                1029
#define IDC_SLIDER_XPOS                 1030
#define IDC_GREEN_SPIN                  1030
#define IDC_SLIDER_YPOS                 1031
#define IDC_RED_SPIN                    1031
#define IDC_SLIDER_ZPOS                 1032
#define IDC_XPOS_EDIT                   1033
#define IDC_OUT_FACTOR_SPIN             1033
#define IDC_YPOS_EDIT                   1034
#define IDC_INHERITANCE_FACTOR_SPIN     1034
#define IDC_GRAYSCALE_CHECK             1035
#define IDC_RADIO1                      1036
#define IDC_LIGHTING_CHECKBOX           1036
#define IDC_PARTICLE_CAP_MAX_RADIO      1036
#define IDC_CHANNEL_DIFFUSE_RADIO       1036
#define IDC_BOX_RADIO                   1036
#define IDC_16BIT                       1036
#define IDC_RADIO2                      1037
#define IDC_BACKGROUND_CHECKBOX         1037
#define IDC_PARTICLE_CAP_TIME_RADIO     1037
#define IDC_CHANNEL_SPECULAR_RADIO      1037
#define IDC_8BIT                        1037
#define IDC_RADIO3                      1038
#define IDC_CAMERA_CHECKBOX             1038
#define IDC_CHANNEL_BOTH_RADIO          1038
#define IDC_BROWSE_BUTTON               1039
#define IDC_SPHERE_RADIO                1039
#define IDC_FILENAME_EDIT               1040
#define IDC_CYLINDER_RADIO              1040
#define IDC_HIERARCHY_LIST              1041
#define IDC_SWITCH_UP_SPIN              1043
#define IDC_SWITCH_DN_SPIN              1044
#define IDC_SWITCH_UP_EDIT              1045
#define IDC_SWITCH_DN_EDIT              1046
#define IDC_CURR_OBJ                    1047
#define IDC_HIERARCHY_NAME              1048
#define IDC_FRAME_COUNT                 1049
#define IDC_FRAME_RATE                  1050
#define IDC_BLEND                       1051
#define IDC_SMALL                       1053
#define IDC_PARTICLE_CAP_MAX_EDIT       1056
#define IDC_MAX_PARTICLES_EDIT          1056
#define IDC_PARTICLE_EMITION_RATE_EDIT  1057
#define IDC_EMISSION_RATE_EDIT          1057
#define IDC_PARTICLE_CAP_TIME_EDIT      1058
#define IDC_ACCELERATION_Y_EDIT         1058
#define IDC_BURST_SIZE_EDIT             1058
#define IDC_PARTICLE_LIFETIME_EDIT      1059
#define IDC_MERGE_ABORT_FACTOR_EDIT     1059
#define IDC_PARTICLE_LIFETIME_SPIN      1060
#define IDC_UVTILING_EDIT               1060
#define IDC_PARTICLE_CAP_CHECKBOX       1061
#define IDC_ACCELERATION_Z_EDIT         1061
#define IDC_UPERSEC_EDIT                1061
#define IDC_VELOCITY_X_EDIT             1062
#define IDC_PARTICLE_POSITION_RANDOM_EDIT 1062
#define IDC_VPERSEC_EDIT                1062
#define IDC_VELOCITY_Y_EDIT             1063
#define IDC_VELOCITY_Z_EDIT             1064
#define IDC_VELOCITY_RANDOM_EDIT        1065
#define IDC_VELOCITY_RANDOM_SPIN        1066
#define IDC_ELASTICITY_EDIT             1067
#define IDC_ELASTICITY_SPIN             1068
#define IDC_OUT_FACTOR_EDIT             1068
#define IDC_ACCELERATION_X_EDIT         1069
#define IDC_ACCELERATION_X_SPIN         1070
#define IDC_COLLIDEABLE_CHECKBOX        1071
#define IDC_INHERITANCE_FACTOR_EDIT     1071
#define IDC_SPHERE_RADIUS_EDIT          1071
#define IDC_SPHERE_RADIUS_SPIN          1072
#define IDC_START_COLOR_BUTTON          1073
#define IDC_CYLINDER_RADIUS_EDIT        1073
#define IDC_START_OPACITY_SLIDER        1074
#define IDC_CYLINDER_RADIUS_SPIN        1074
#define IDC_END_COLOR_BUTTON            1075
#define IDC_CYLINDER_HEIGHT_EDIT        1075
#define IDC_END_OPACITY_SLIDER          1076
#define IDC_CYLINDER_HEIGHT_SPIN        1076
#define IDC_FADE_TIME_EDIT              1077
#define IDC_PARTICLE_END_SIZE_EDIT      1078
#define IDC_FADE_TIME_SPIN              1078
#define IDC_TYPE_COMBO                  1079
#define IDC_BACK                        1079
#define IDC_NAME_EDIT                   1080
#define IDC_LARGE                       1080
#define IDC_PARTICLE_START_SIZE_EDIT    1081
#define IDC_DETAILS                     1081
#define IDC_PARTICLE_START_SIZE_SPIN    1082
#define IDC_PARTICLE_END_SIZE_SPIN      1083
#define IDC_END_OPACITY_EDIT            1084
#define IDC_BONE_TREE                   1086
#define IDC_ATTACH_BUTTON               1087
#define IDC_OBJECT_COMBO                1088
#define IDC_BONE_GROUPBOX               1089
#define IDC_VOLUME_SLIDER               1089
#define IDC_TREE1                       1090
#define IDC_COLOR_WINDOW                1092
#define IDC_TEXTURE_FILENAME            1093
#define IDC_RESIZEABLE_CHECK            1096
#define IDC_MIPMAP_OFF_CHECK            1097
#define IDC_CLAMPU_CHECK                1098
#define IDC_CLAMPV_CHECK                1099
#define IDC_ALPHA_CHECK                 1100
#define IDC_ANIMATION_CHECK             1103
#define IDC_TOOLBAR_SLOT                1104
#define IDC_PRIORITY_SLIDER             1104
#define IDC_TEXTURE_THUMBNAIL           1105
#define IDC_DROP_OFF_EDIT               1105
#define IDC_VERSION                     1106
#define IDC_MAX_VOL_EDIT                1106
#define IDC_CHECK1                      1107
#define IDC_2D_RADIO                    1107
#define IDC_INTENSITY_SLIDER            1108
#define IDC_3D_RADIO                    1108
#define IDC_END_ATTENUATION_SPIN        1109
#define IDC_SOUNDEFFECT_RADIO           1109
#define IDC_START_ATTENUATION_SPIN      1110
#define IDC_MUSIC_RADIO                 1110
#define IDC_DISTANCE_SPIN               1111
#define IDC_ATTENUATION_CHECK           1113
#define IDC_SHADER_COMBO                1117
#define IDC_MAX_PARTICLES_CHECK         1118
#define IDC_MERGE_INTERSECTIONS_CHECK   1119
#define IDC_BOX_X_EDIT                  1120
#define IDC_END_CAPS_CHECK              1120
#define IDC_BOX_Y_EDIT                  1121
#define IDC_DISABLE_SORTING_CHECK       1121
#define IDC_BOX_Z_EDIT                  1122
#define IDC_BOX_X_SPIN                  1123
#define IDC_BOX_Y_SPIN                  1124
#define IDC_BOX_Z_SPIN                  1125
#define IDC_SPHERE_HOLLOW_CHECK         1126
#define IDC_SPECIFY_CREATION_VOLUME     1127
#define IDC_PLAY_SOUND_EFFECT           1127
#define IDC_SIZE_RANDOM_SPIN            1128
#define IDC_SIZE_RANDOM_EDIT            1129
#define IDC_SIZE_Y_SPIN                 1129
#define IDC_TRIGGER_RADIUS_EDIT         1129
#define IDC_STOP_SOUND_EFFECT           1129
#define IDC_SIZE_EDIT                   1130
#define IDC_SIZE_Z_SPIN                 1130
#define IDC_OUTER_SIZE_Y_SPIN           1130
#define IDC_FILENAME                    1130
#define IDC_SIZE_SPIN                   1131
#define IDC_SPECIFY_VELOCITY_RANDOM     1132
#define IDC_ANIMATION_LIST              1134
#define IDC_FOV_CHECK                   1136
#define IDC_CLIP_PLANE_CHECK            1137
#define IDC_PARTICLE_LIFETIME_CHECK     1138
#define IDC_BROWSE1                     1141
#define IDC_BROWSE2                     1142
#define IDC_RESOLUTION_LIST_CTRL        1144
#define IDC_FULLSCREEN_CHECK            1145
#define IDC_LIFETIME_EDIT               1146
#define IDC_LIFETIME_SPIN               1147
#define IDC_OPACITY_VECTOR_CHECK        1148
#define IDC_TEXTURE_TILE_EDIT           1148
#define IDC_SCALE_BAR_X                 1149
#define IDC_INVERT_VECTOR_CHECK         1149
#define IDC_TEXTURE_TILE_SPIN           1149
#define IDC_SIZE_X_SPIN                 1150
#define IDC_CAMERA_ALIGNED_CHECK        1151
#define IDC_OUTER_SIZE_X_SPIN           1151
#define IDC_LOOPING_CHECK               1152
#define IDC_OUTER_SCALE_BAR_X           1152
#define IDC_INNER_SIZE_X_EDIT           1153
#define IDC_INNER_SIZE_Y_EDIT           1154
#define IDC_SLIDER_Y                    1155
#define IDC_INNER_SIZE_X_SPIN           1155
#define IDC_SLIDER_Z                    1156
#define IDC_INNER_SIZE_Y_SPIN           1156
#define IDC_INNER_SCALE_BAR_X           1157
#define IDC_INNER_SCALE_BAR_Y           1158
#define IDC_OBJECT                      1159
#define IDC_PROMPT                      1160
#define IDC_MAPMODE_COMBO               1161
#define IDC_SUBDIVISION_LEVEL_EDIT      1162
#define IDC_SUBDIVISION_LEVEL_SPIN      1163
#define IDC_NOISE_AMPLITUDE_EDIT        1164
#define IDC_NOISE_AMPLITUDE_SPIN        1165
#define IDC_RENDER_MODE_COMBO           1166
#define IDC_ROTATION_RANDOM_EDIT        1167
#define IDC_ROTATION_RANDOM_SPIN        1168
#define IDC_FRAME_LAYOUT_COMBO          1169
#define IDC_INITIAL_ORIENTATION_RANDOM_EDIT 1169
#define IDC_ROTATION_BAR                1170
#define IDC_FRAME_BAR                   1171
#define IDC_INITIAL_ORIENTATION_RANDOM_SPIN 1171
#define IDC_FRAME_RANDOM_SPIN           1172
#define IDC_FRAME_RANDOM_EDIT           1173
#define IDC_ROTATION_EDIT               1174
#define IDC_ROTATION_SPIN               1175
#define IDC_FRAME_EDIT                  1176
#define IDC_FRAME_SPIN                  1177
#define IDC_BLUR_TIME_RANDOM_EDIT       1178
#define IDC_BLUR_TIME_RANDOM_SPIN       1179
#define IDC_BLUR_TIME_BAR               1180
#define IDC_BLUR_TIME_EDIT              1181
#define IDC_BLUR_TIME_SPIN              1182
#define IDC_COMPRESSQ                   1183
#define IDC_GAMMA_SLIDER                1186
#define IDC_GAMMA_DISPLAY               1187
#define IDC_INSTRUCTIONS                1188
#define IDD_BROWSE_DIR                  1536
#define IDD_BROWSE_DIRECTORY            20638
#define IDD_XXX_BROWSE_DIRECTORY        20638
#define IDD_PROP_PAGE_SPHERE_GEN        20639
#define IDD_PROP_PAGE_SPHERE_COLOR      20640
#define IDD_PROP_PAGE_SPHERE_SCALE      20641
#define IDD_SCALE_KEY                   20642
#define IDD_PROP_PAGE_RING_SCALE        20643
#define IDD_PROP_PAGE_RING_GEN          20644
#define IDD_PROP_PAGE_RING_COLOR        20645
#define IDD_PROP_PAGE_EMITTER_LINEPROPS 20646
#define IDD_PROP_PAGE_EMITTER_ROTATION  20647
#define IDD_PROP_PAGE_EMITTER_FRAME     20648
#define IDD_PARTICLE_ROTATION_KEY       20649
#define IDD_PARTICLE_FRAME_KEY          20650
#define IDM_OBJECT_PROPERTIES           32771
#define IDM_ANI_PAUSE                   32772
#define IDM_ANI_STOP                    32773
#define IDM_ANI_REWIND                  32774
#define IDM_ANI_START                   32775
#define IDM_LOD_GENERATE                32776
#define IDM_LOD_SET_SWITCH              32777
#define IDM_ANI_SPEED                   32778
#define IDM_CAMERA_TOP                  32779
#define IDM_CAMERA_FRONT                32780
#define IDM_CAMERA_LEFT                 32781
#define IDM_CAMERA_BOTTOM               32782
#define IDM_CAMERA_BACK                 32783
#define IDM_CAMERA_RIGHT                32784
#define IDM_CAMERA_RESET                32785
#define IDM_OBJECT_ROTATE_Z             32786
#define IDM_OBJECT_ROTATE_X             32787
#define IDM_OBJECT_ROTATE_Y             32788
#define IDM_LIGHT_AMBIENT               32789
#define IDM_LIGHT_SCENE                 32790
#define IDM_BACKGROUND_COLOR            32791
#define IDM_BACKGROUND_BMP              32792
#define IDM_BACKGROUND_MESH             32793
#define IDM_BACKGROUND_OBJECT           32793
#define IDM_LOD_SAVE                    32794
#define IDM_LOD_SAVEALL                 32795
#define IDM_SAVE_SETTINGS               32796
#define IDM_LOAD_SETTINGS               32797
#define IDM_VIEW_OBJECT_BAR             32798
#define IDM_VIEW_ANIMATION_BAR          32799
#define IDM_ANI_STEP_FWD                32800
#define IDM_ANI_STEP_BKWD               32801
#define IDM_CAMERA_ALLOW_ROTATE_X       32802
#define IDM_CAMERA_ALLOW_ROTATE_Y       32803
#define IDM_CAMERA_ALLOW_ROTATE_Z       32804
#define IDM_OBJECT_RESET                32805
#define IDM_DEVICE_CHANGE               32806
#define IDM_VIEW_FULLSCREEN             32807
#define IDM_CREATE_EMITTER              32808
#define IDM_EDIT_EMITTER                32809
#define IDM_SAVE_EMITTER                32810
#define IDM_BONE_MANAGEMENT             32811
#define IDM_BONE_AUTO_ASSIGN            32812
#define IDM_SAVE_AGGREGATE              32813
#define IDM_CAMERA_ANIMATE              32814
#define IDM_CAMERA_RESET_ON_LOAD        32815
#define IDM_INC_AMBIENT_LIGHT           32816
#define IDM_DEC_AMBIENT_LIGHT           32817
#define IDM_INC_LIGHT                   32818
#define IDM_DEC_LIGHT                   32819
#define IDM_OBJECT_ROTATE_Z_BACK        32820
#define IDM_OBJECT_ROTATE_Y_BACK        32821
#define IDM_LIGHT_ROTATE_Y              32822
#define IDM_LIGHT_ROTATE_Y_BACK         32823
#define IDM_LIGHT_ROTATE_Z              32824
#define IDM_LIGHT_ROTATE_Z_BACK         32825
#define IDM_MAKE_AGGREGATE              32826
#define IDM_REPLACE_TEXTURES            32827
#define IDM_RENAME_AGGREGATE            32828
#define IDM_CRASH_APP                   32830
#define IDM_LOD_RECORD_SCREEN_AREA      32831
#define IDM_LOD_NEXT_LEVEL              32832
#define IDM_LOD_INCLUDE_NULL            32833
#define IDM_LOD_PREV_LEVEL              32834
#define IDM_LOD_AUTOSWITCH              32835
#define IDM_SETTINGS1                   32836
#define IDM_SETTINGS2                   32837
#define IDM_SETTINGS3                   32838
#define IDM_SETTINGS4                   32839
#define IDC_LIST                        32840
#define IDM_SETTINGS5                   32840
#define IDM_SETTINGS6                   32841
#define IDM_SETTINGS7                   32842
#define IDM_SETTINGS8                   32843
#define IDM_SETTINGS9                   32844
#define IDM_MAKE_MOVIE                  32845
#define IDM_SAVE_SCREENSHOT             32846
#define IDM_ADD_DAMAGE                  32847
#define IDM_REMOVE_DAMAGE               32848
#define IDM_SLIDESHOW_UP                32849
#define IDM_SLIDESHOW_DOWN              32850
#define IDM_ADVANCED_ANIM               32852
#define IDM_CAMERA_SETTINGS             32853
#define IDM_COPY_SCREEN_SIZE            32854
#define IDC_LIST_MISSING_TEXTURES       32855
#define IDC_COPY_ASSETS                 32861
#define IDC_PROPAGATE                   32862
#define IDM_TEXTURE_PATH                32863
#define IDM_CHANGE_RESOLUTION           32864
#define IDM_LIGHTING_EXPOSE             32865
#define IDM_CREATE_SPHERE               32866
#define IDM_CREATE_RING                 32867
#define IDM_EDIT_PRIMITIVE              32868
#define IDM_EXPORT_PRIMITIVE            32869
#define ID_FILE_IMPORT_PHONEME          32870
#define ID_FILE_IMPORT_FACIAL_ANIMS     32870
#define IDM_KILL_SCENE_LIGHT            32871
#define IDC_ADD_TO_LINEUP               32872
#define IDC_REMOVE_FROM_LINEUP          32873
#define IDM_IMPORT_FACIAL_ANIMS         32874
#define IDM_RESTRICT_ANIMS              32875
#define IDM_BIND_SUBOBJECT_LOD          32876
#define IDM_SET_CAMERA_DISTANCE         32877
#define IDM_OBJECT_ALTERNATE_MATERIALS  32878
#define IDM_CREATE_SOUND_OBJECT         32879
#define IDM_EDIT_SOUND_OBJECT           32880
#define IDM_EXPORT_SOUND_OBJ            32881
#define IDM_WIREFRAME_MODE              32882
#define IDM_BACKGROUND_FOG              32883
#define IDM_SCALE_EMITTER               32884
#define IDM_TOGGLE_SORTING              32885
#define IDM_CAMERA_BONE_POS_X           32886
#define ID_VIEW_SUBDIVISION_1           32888
#define ID_VIEW_SUBDIVISION_2           32889
#define ID_VIEW_SUBDIVISION_3           32890
#define ID_VIEW_SUBDIVISION_4           32891
#define ID_VIEW_SUBDIVISION_5           32892
#define ID_VIEW_SUBDIVISION_6           32893
#define ID_VIEW_SUBDIVISION_7           32894
#define ID_VIEW_SUBDIVISION_8           32895
#define ID_VIEW_PATCH_GAP_FILL          32896
#define IDM_MUNGE_SORT_ON_LOAD          32897
#define IDM_ENABLE_GAMMA_CORRECTION     32898
#define IDM_SET_GAMMA                   32899
#define IDM_EDIT_ANIMATED_SOUNDS_OPTIONS 32900
#define IDM_PRELIT_VERTEX               32910
#define IDM_PRELIT_MULTIPASS            32911
#define IDM_PRELIT_MULTITEX             32912
#define IDS_MESH_PROP_DESC              61204
#define IDS_MESH_PROP_TITLE             61205
#define IDS_HIERARCHY_PROP_DESC         61206
#define IDS_HIERARCHY_PROP_TITLE        61207
#define IDS_CANT_GEN_LOD_MSG            61208
#define IDS_CANT_GEN_LOD_TITLE          61209
#define IDS_POLY_PANE                   61210
#define IDS_DISTANCE_PANE               61211
#define IDS_FRAME_PANE                  61212
#define IDS_ANI_PROP_DESC               61213
#define IDS_ANIMATION_PROP_TITLE        61214
#define IDS_EMITTER_PROP_TITLE          61215
#define IDS_VERSION                     61216
#define IDS_UNACCEPTABLE_GLIDE_MSG      61217
#define IDS_PARTICLE_PANE               61218
#define IDS_FPS_PANE                    61219
#define IDS_SPHERE_PROP_TITLE           61220
#define IDS_RING_PROP_TITLE             61221
#define IDS_RESOLUTION_PANE             61222

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        206
#define _APS_NEXT_COMMAND_VALUE         32901
#define _APS_NEXT_CONTROL_VALUE         1189
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
